### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#31]
2.0 introduces BREAKING CHANGES

- [x] Waiting for latest vscode integration typescript 3.8
- [x] **BREAKING CHANGES** Remove `deno.enable`/`deno.disable` command. #24
- [x] **BREAKING CHANGES** Port to `dprint` formatter and only support typescript/javascript file. prettier configuration will be ignore. await https://github.com/denoland/deno/issues/3877 close #20
- [x] **BREAKING CHANGES** rename configuration `deno.dtsFilepaths` to `deno.dts_file`
- [ ] ~Built-in Deno version manager. Easily switch Deno versions within vscode~ (Out of Scope)
- [x] Support import-maps #3 
- [x] Fully i18n supported.
- [x] support external type definitions #35
